"""Add reservation related tables

Revision ID: f9601fb1666c
Revises: dc014eee56eb
Create Date: 2026-01-07 23:53:51.585112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9601fb1666c'
down_revision: Union[str, Sequence[str], None] = 'dc014eee56eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('reservations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('fee_per_person', sa.Integer(), nullable=False),
    sa.Column('allow_multi_payer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_issue_invoice', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(), nullable=False),
    sa.Column('payer_name', sa.String(length=100), nullable=False),
    sa.Column('payer_email', sa.String(length=100), nullable=False),
    sa.Column('payer_phone', sa.String(length=20), nullable=False),
    sa.Column('amount_twd', sa.Integer(), nullable=False),
    sa.Column('payment_provider', sa.String(32), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('merchant_order_no', sa.String(length=30), nullable=True),
    sa.Column('trade_no', sa.String(length=20), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_payments_merchant_order_no'), 'payments', ['merchant_order_no'], unique=True)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index('ix_payments_reservation_status', 'payments', ['reservation_id', 'status'], unique=False)
    
    op.create_table('reservation_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reservation_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_participants')
    op.drop_index('ix_payments_reservation_status', table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_order_no'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('reservations')
    op.drop_table('players')
    # ### end Alembic commands ###
